blank_issues_enabled: true
contact_links:
  - name: NuGet.org Issue Tracker
    url: https://github.com/NuGet/NuGetGallery
    about: Please file issues about NuGet.org itself here.
  - name: NuGet Security Reports
    url: mailto:security@nuget.org
    about: Please report security vulnerabilities here.
